const { chromium } = require("playwright-core");
const EXE = (process.env.CHROMIUM || "/opt/pw-browsers/chromium-1194/chrome-linux/chrome");
const out=[]; const ok=(n,c,x="")=>out.push(`${c?"PASS ✅":"FAIL ❌"}  ${n}${x?"  — "+x:""}`);
const clock=(iso)=>`(function(){var F=new (window.Date)("${iso}").getTime();var D=window.Date;function M(){if(arguments.length===0)return new D(F);return new D(...arguments);}M.now=()=>F;M.parse=D.parse;M.UTC=D.UTC;M.prototype=D.prototype;window.Date=M;})();`;
(async()=>{
  const b=await chromium.launch({executablePath:EXE});
  const ctx=await b.newContext({viewport:{width:390,height:1400},isMobile:true});
  await ctx.route("**/gstatic.com/**",r=>r.fulfill({status:200,contentType:"text/javascript",body:""}));
  const page=await ctx.newPage();
  const errs=[]; page.on("pageerror",e=>errs.push(e.message));
  await page.addInitScript(clock("2026-07-19T14:00:00"));
  await page.addInitScript(()=>{ localStorage.clear(); localStorage.setItem("thirstyboys.me","1"); });
  await page.goto("http://localhost:8735/index.html",{waitUntil:"domcontentloaded"});
  await page.waitForTimeout(600);
  await page.evaluate(()=>{
    const m=document.getElementById("whoami-modal"); if(m)m.classList.add("hidden");
    state.tallies=[{pint:14,wine:2,coffee:2},{pint:18,gandt:4,soft:1},{pint:9,wine:5},{pint:11,soft:2}];
    state.log=[]; let id=0; const add=(iso,who,dr)=>state.log.push({id:"r"+(id++),who,drink:dr,ts:new Date(iso).getTime()});
    ["12:40","13:15","14:21","16:30","20:10"].forEach((t,i)=>add("2026-07-17T"+t,i%4,"pint"));
    ["12:30","16:20","20:15","22:10"].forEach((t,i)=>add("2026-07-18T"+t,i%4,"pint"));
    ["11:00"].forEach((t,i)=>add("2026-07-19T"+t,0,"pint"));
    state.bingo={villa:0,canal:1,peaky:1};
    state.bets={round1:{calls:{0:0,1:1},result:0,revealed:true},toca:{calls:{0:1,1:1},result:1,revealed:true}};
    save(); render();
  });
  await page.waitForTimeout(300);
  const t = ()=>page.evaluate(()=>document.getElementById("recap-card").textContent);
  ok("recap default tab after trip", await page.evaluate(()=>document.getElementById("recap").style.display!=="none"));
  ok("shows per-head tile", /Per head/i.test(await t()));
  ok("shows biggest hour tile", /Biggest hour/i.test(await t()));
  ok("shows per-drink breakdown chips", await page.locator("#recap-card .rc-chip").count() >= 3);
  ok("shows Fri/Sat/Sun day split", await page.locator("#recap-card .recap-days").count() === 1);
  ok("shows sharpest odds (bet accuracy)", /Sharpest odds/i.test(await t()));
  ok("no 'Most voted-for' (awards removed)", !/Most voted-for/i.test(await t()));
  ok("shows top bingo spotter", /Top spotter/i.test(await t()));
  ok("share text includes the new stats", await page.evaluate(()=>{ const s=buildRecapText(); return /total/.test(s)&&/each/.test(s)&&/Bingo/.test(s); }));
  ok("no errors", errs.length===0, errs.join(" | "));
  console.log(out.join("\n"));
  const p=out.filter(x=>x.startsWith("PASS")).length;
  console.log(`\n${p}/${out.length} wrapped checks passed`);
  await b.close();
  process.exit(p===out.length?0:1);
})();
